---
- name: Install yum-utils
  yum:
    name: 'yum-utils'
    state: present
  become: true

- name: Installing HashiCorp repository for Amazon Linux
  get_url:
    url: https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install Boundary
  yum:
    name: "boundary-{{ boundary_version }}"
    state: present
    update_cache: true
  become: true
  when: not boundary_enterprise

- name: Install Boundary Enterprise
  yum:
    name: "boundary-enterprise-{{ boundary_version }}+ent"
    state: present
    update_cache: true
  become: true
  when: boundary_enterprise
