---
- name: Install yum-utils
  yum:
    name: 'yum-utils'
    state: present
  become: true

- name: Hashicorp Repo
  command: "yum-config-manager --add-repo {{ boundary_yum_repo }}"
  args:
    creates: /etc/yum.repos.d/hashicorp.repo
  become: true

- name: Install Boundary
  yum:
    name: "boundary-{{ boundary_version }}"
  become: true